ARG BASE_IMAGE=alpine:3.22
FROM ${BASE_IMAGE} AS base

ARG BASE_IMAGE_NAME
ARG BASE_IMAGE_TAG

#include "common.alpine"

#include "common.gosu"

FROM base AS final

#include "common.label-and-env"

# Fix PATH for perl
#ENV PATH="/usr/bin/vendor_perl:$PATH"

VOLUME [ "/work" ]
WORKDIR /work

#include "common.entrypoint"

CMD ["/bin/bash", "-l"]
