ARG BASE_IMAGE=archlinux:base
FROM ${BASE_IMAGE} AS base

#include "common.archlinux"

#include "common.gosu"

FROM base AS final

#include "common.label-and-env"

# Fix PATH for perl
ENV PATH="/usr/bin/vendor_perl:$PATH"

VOLUME [ "/work" ]
WORKDIR /work

#include "common.entrypoint"

CMD ["/bin/bash", "-l"]
