ARG BASE_IMAGE=archlinux:base
FROM ${BASE_IMAGE} AS base

# ARG BASE_IMAGE_NAME
# ARG BASE_IMAGE_TAG

### @INCLUDE common.archlinux ###

FROM base AS final

### @INCLUDE common.label-and-env ###

# Fix PATH for perl
ENV PATH="/usr/bin/vendor_perl:$PATH"

VOLUME [ "/work" ]
WORKDIR /work

### @INCLUDE common.entrypoint ###
