ARG BASE_IMAGE=ubuntu:24.04
FROM ${BASE_IMAGE} AS base

#include "common.debian"

#include "common.gosu"

FROM base AS final

#include "common.label-and-env"

# Fix PATH for perl
ENV PATH="/usr/bin/vendor_perl:$PATH"

VOLUME [ "/work" ]
WORKDIR /work

#include "common.entrypoint"

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash", "-l"]
