ARG BASE_IMAGE=debian:bookworm
FROM ${BASE_IMAGE} AS base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install \
# Core multimedia tools
    ffmpeg \
    x264 \
    x265 \
    melt \
    multimon-ng \
    nageru \
# AV1
    dav1d \
    rav1e \
    svt-av1 \
    libheif-dev \
    libavif-dev \
    libavif-bin \
    libaom-dev \
# JPEG
    jpegoptim \
    libjpeg-dev \
    libopenjp2-7-dev \    
    libjxl-dev \
    libjxl-tools \
# WebP
    webp \
    webp-pixbuf-loader \
    handbrake-cli \
# Audio and Video Effects Plugins
    ladspa-sdk \
    frei0r-plugins-dev \
# Image and Video Processing
    libopencv-dev \
    imagemagick \
    libwmf-dev \
    libopenraw-dev \
    libraw-dev \
    libpng-dev \
# MIDI & Audio
    timidity \
    mencoder \
    sox \
    vorbis-tools \
    flac \
    lame \
    libopusenc-dev \
# Developer Tools
    build-essential \
    libdevil-dev \
    libhdf5-dev \
    libzip-dev \
    djvulibre-bin \
    wavpack \
    openmpi-bin \
# File and Metadata Management
    gvfs \
    mat2 \
    libffms2-dev \
# DVD & MPEG-2
    twolame \
# HDR
# PDF Tools
    ghostscript \
    exiv2 \
    img2pdf \
# Utilities
    mediainfo \
    ffmpegthumbnailer \
    mkvtoolnix \
    yt-dlp \
    atomicparsley \
    aria2 \
# Python Libraries
    python3-mutagen \
    python3-pycryptodome \
    python3-secretstorage \
    python3-websockets \
    python3-xattr \
# RTMP Streaming
    rtmpdump \
# Compression Tools
    xz-utils \
    gzip \
    bzip2 \
    tar \    
    zstd \
# Shell Enhancements
    bash-completion \
    && apt-get clean \
    && apt-get -y autoremove --purge \
    && rm -rf /var/lib/apt/lists/*

# Not found: av1an libdvdcss dsp avisynthplus-dev libultrahdr-dev python3-pycryptodomex
# Conflicts: python3-pyxattr

FROM base AS final

#include "common.label-and-env"

# Fix PATH for perl
ENV PATH="/usr/bin/vendor_perl:$PATH"

VOLUME [ "/work" ]
WORKDIR /work

COPY --from=root-project common/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh && chown root:root /entrypoint.sh

#ARG USERNAME=user
#RUN useradd -m "${USERNAME}"
# Add color to bash
#RUN echo PS1="'\[\033[01;32m\][\u@\h\[\033[01;37m\] \W\[\033[01;32m\]]\$\[\033[00m\] '" >> "/home/${USERNAME}/.bashrc"
#USER ${USERNAME}

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash", "-l"]

