name: multimedia-docker-images

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  multimedia-docker-images:
    name: multimedia:${{ matrix.images.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ["archlinux"]
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
#          submodules: 'recursive'
          fetch-depth: 1
#      - name: Install dependencies
#        run: sudo apt-get update && sudo apt-get install 
      - name: Build
        run: make ${{ matrix.image }}
      - name: Test the image
        run: CPUS=2.0 make ${{ matrix.image }}.test
      - name: clean the image
        run: make ${{ matrix.image }}.clean
      - name: purge the image
        run: make ${{ matrix.image }}.purge
#      - name: "Push to hub.docker.com"
#        if: github.ref == 'refs/heads/main'
#        run: |
#            echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
#            make ${{ matrix.image }}.push
